---
gitlab:
  image: 'gitlab/gitlab-ce:9.1.0-ce.0'
  restart: always
  hostname: 'gitlab.arifrosada.com'
  links:
    - postgresql:postgresql
    - redis:redis
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      postgresql['enable'] = false
      gitlab_rails['db_username'] = "usernamenyapa"
      gitlab_rails['db_password'] = "passwordnyapa"
      gitlab_rails['db_host'] = "postgresql"
      gitlab_rails['db_port'] = "5432"
      gitlab_rails['db_database'] = "production"
      gitlab_rails['db_adapter'] = 'postgresql'
      gitlab_rails['db_encoding'] = 'utf8'
      redis['enable'] = false
      gitlab_rails['redis_host'] = 'redis'
      gitlab_rails['redis_port'] = '6379'
      external_url 'http://gitlab.arifrosada.com:30080'
      gitlab_rails['gitlab_shell_ssh_port'] = 30022
  ports:
    # both ports must match the port from external_url above
    - "30080:30080"
    # the mapped port must match ssh_port specified above.
    - "30022:22"

postgresql:
  restart: always
  image: postgres:9.6.2-alpine
  environment:
    - POSTGRES_USER=usernyaapa
    - POSTGRES_PASSWORD=passwordnyapa
    - POSTGRES_DB=gitlabhq_production

redis:
  restart: always
  image: redis:3.0.7-alpine
jenkins:
  restart: always
  image: orchardup/jenkins
  ports:
    - "8080:8080"
